FROM python:3.10-slim

RUN apt-get update && apt-get install -y gcc

COPY server /app

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5555

CMD ["python", "server_serial.py"]

# docker build -t zmq-server -f Dockerfile.server .
# docker run -it -p 5555:5555 zmq-server
# docker run -it -d -p 5555:5555 zmq-server